/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'created' : Time,
  'principal' : IDL.Principal,
  'lastReset' : Time,
  'tier' : IDL.Text,
  'tokenBalance' : IDL.Int,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : Time,
});
export const ImageRequest = IDL.Record({
  'style' : IDL.Text,
  'timestamp' : Time,
  'prompt' : IDL.Text,
});
export const GameScore = IDL.Record({
  'user' : IDL.Principal,
  'score' : IDL.Int,
  'timestamp' : Time,
  'gameName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addImageRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'consumeTokens' : IDL.Func([IDL.Int, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getImageHistory' : IDL.Func([], [IDL.Vec(ImageRequest)], ['query']),
  'getTopScores' : IDL.Func([IDL.Text], [IDL.Vec(GameScore)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([], [], []),
  'resetMonthlyTokens' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveScore' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'upgradeToPremium' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'created' : Time,
    'principal' : IDL.Principal,
    'lastReset' : Time,
    'tier' : IDL.Text,
    'tokenBalance' : IDL.Int,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : Time,
  });
  const ImageRequest = IDL.Record({
    'style' : IDL.Text,
    'timestamp' : Time,
    'prompt' : IDL.Text,
  });
  const GameScore = IDL.Record({
    'user' : IDL.Principal,
    'score' : IDL.Int,
    'timestamp' : Time,
    'gameName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addImageRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'consumeTokens' : IDL.Func([IDL.Int, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getImageHistory' : IDL.Func([], [IDL.Vec(ImageRequest)], ['query']),
    'getTopScores' : IDL.Func([IDL.Text], [IDL.Vec(GameScore)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([], [], []),
    'resetMonthlyTokens' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveScore' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'upgradeToPremium' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };